from gym.envs.custom_env.rand_cycle_v0_abs_box import Rand_cycle_v0_abs_box
from gym.envs.custom_env.rand_cycle_v1_abs_box import Rand_cycle_v1_abs_box
from gym.envs.custom_env.rand_cycle_v2_abs_box import Rand_cycle_v2_abs_box
from gym.envs.custom_env.rand_cycle_v3_abs_box import Rand_cycle_v3_abs_box

# relative position
from gym.envs.custom_env.rand_cycle_v3_rel_box import Rand_cycle_v3_rel_box
from gym.envs.custom_env.rand_cycle_v2_rel_box import Rand_cycle_v2_rel_box
from gym.envs.custom_env.rand_cycle_v1_rel_box import Rand_cycle_v1_rel_box
from gym.envs.custom_env.rand_cycle_v1_rel_box_2target import Rand_cycle_v1_rel_box_2target
from gym.envs.custom_env.rand_cycle_v0_rel_box import Rand_cycle_v0_rel_box

# abs position for my_v3
from gym.envs.custom_env.rand_cycle_v3_abs_box import Rand_cycle_v3_abs_box